/**
 * This class stores several arrays of constants to be utilized by the application
 */
public class Util {

    // array of all possible countries to choose (order matters for index handling)
    public static final String[] COUNTRIES = {
                    "Aruba",
                    "Afghanistan",
                    "Angola",
                    "Anguilla",
                    "Åland Islands",
                    "Albania",
                    "Andorra",
                    "United Arab Emirates",
                    "Argentina",
                    "Armenia",
                    "American Samoa",
                    "Antarctica",
                    "French Southern Territories",
                    "Antigua and Barbuda",
                    "Australia",
                    "Austria",
                    "Azerbaijan",
                    "Burundi",
                    "Belgium",
                    "Benin",
                    "Bonaire, Sint Eustatius and Saba",
                    "Burkina Faso",
                    "Bangladesh",
                    "Bulgaria",
                    "Bahrain",
                    "Bahamas",
                    "Bosnia and Herzegovina",
                    "Saint Barthélemy",
                    "Belarus",
                    "Belize",
                    "Bermuda",
                    "Bolivia, Plurinational State of",
                    "Brazil",
                    "Barbados",
                    "Brunei Darussalam",
                    "Bhutan",
                    "Bouvet Island",
                    "Botswana",
                    "Central African Republic",
                    "Canada",
                    "Cocos (Keeling) Islands",
                    "Switzerland",
                    "Chile",
                    "China",
                    "Côte d'Ivoire",
                    "Cameroon",
                    "Congo, the Democratic Republic of the",
                    "Congo",
                    "Cook Islands",
                    "Colombia",
                    "Comoros",
                    "Cape Verde",
                    "Costa Rica",
                    "Cuba",
                    "Curaçao",
                    "Christmas Island",
                    "Cayman Islands",
                    "Cyprus",
                    "Czech Republic",
                    "Germany",
                    "Djibouti",
                    "Dominica",
                    "Denmark",
                    "Dominican Republic",
                    "Algeria",
                    "Ecuador",
                    "Egypt",
                    "Eritrea",
                    "Western Sahara",
                    "Spain",
                    "Estonia",
                    "Ethiopia",
                    "Finland",
                    "Fiji",
                    "Falkland Islands (Malvinas)",
                    "France",
                    "Faroe Islands",
                    "Micronesia, Federated States of",
                    "Gabon",
                    "United Kingdom",
                    "Georgia",
                    "Guernsey",
                    "Ghana",
                    "Gibraltar",
                    "Guinea",
                    "Guadeloupe",
                    "Gambia",
                    "Guinea-Bissau",
                    "Equatorial Guinea",
                    "Greece",
                    "Grenada",
                    "Greenland",
                    "Guatemala",
                    "French Guiana",
                    "Guam",
                    "Guyana",
                    "Hong Kong",
                    "Heard Island and McDonald Islands",
                    "Honduras",
                    "Croatia",
                    "Haiti",
                    "Hungary",
                    "Indonesia",
                    "Isle of Man",
                    "India",
                    "British Indian Ocean Territory",
                    "Ireland",
                    "Iran, Islamic Republic of",
                    "Iraq",
                    "Iceland",
                    "Israel",
                    "Italy",
                    "Jamaica",
                    "Jersey",
                    "Jordan",
                    "Japan",
                    "Kazakhstan",
                    "Kenya",
                    "Kyrgyzstan",
                    "Cambodia",
                    "Kiribati",
                    "Saint Kitts and Nevis",
                    "Korea, Republic of",
                    "Kuwait",
                    "Lao People's Democratic Republic",
                    "Lebanon",
                    "Liberia",
                    "Libya",
                    "Saint Lucia",
                    "Liechtenstein",
                    "Sri Lanka",
                    "Lesotho",
                    "Lithuania",
                    "Luxembourg",
                    "Latvia",
                    "Macao",
                    "Saint Martin (French part)",
                    "Morocco",
                    "Monaco",
                    "Moldova, Republic of",
                    "Madagascar",
                    "Maldives",
                    "Mexico",
                    "Marshall Islands",
                    "Macedonia, the former Yugoslav Republic of",
                    "Mali",
                    "Malta",
                    "Myanmar",
                    "Montenegro",
                    "Mongolia",
                    "Northern Mariana Islands",
                    "Mozambique",
                    "Mauritania",
                    "Montserrat",
                    "Martinique",
                    "Mauritius",
                    "Malawi",
                    "Malaysia",
                    "Mayotte",
                    "Namibia",
                    "New Caledonia",
                    "Niger",
                    "Norfolk Island",
                    "Nigeria",
                    "Nicaragua",
                    "Niue",
                    "Netherlands",
                    "Norway",
                    "Nepal",
                    "Nauru",
                    "New Zealand",
                    "Oman",
                    "Pakistan",
                    "Panama",
                    "Pitcairn",
                    "Peru",
                    "Philippines",
                    "Palau",
                    "Papua New Guinea",
                    "Poland",
                    "Puerto Rico",
                    "Korea, Democratic People's Republic of",
                    "Portugal",
                    "Paraguay",
                    "Palestine, State of",
                    "French Polynesia",
                    "Qatar",
                    "Réunion",
                    "Romania",
                    "Russian Federation",
                    "Rwanda",
                    "Saudi Arabia",
                    "Sudan",
                    "Senegal",
                    "Singapore",
                    "South Georgia and the South Sandwich Islands",
                    "Saint Helena, Ascension and Tristan da Cunha",
                    "Svalbard and Jan Mayen",
                    "Solomon Islands",
                    "Sierra Leone",
                    "El Salvador",
                    "San Marino",
                    "Somalia",
                    "Saint Pierre and Miquelon",
                    "Serbia",
                    "South Sudan",
                    "Sao Tome and Principe",
                    "Suriname",
                    "Slovakia",
                    "Slovenia",
                    "Sweden",
                    "Swaziland",
                    "Sint Maarten (Dutch part)",
                    "Seychelles",
                    "Syrian Arab Republic",
                    "Turks and Caicos Islands",
                    "Chad",
                    "Togo",
                    "Thailand",
                    "Tajikistan",
                    "Tokelau",
                    "Turkmenistan",
                    "Timor-Leste",
                    "Tonga",
                    "Trinidad and Tobago",
                    "Tunisia",
                    "Turkey",
                    "Tuvalu",
                    "Taiwan, Province of China",
                    "Tanzania, United Republic of",
                    "Uganda",
                    "Ukraine",
                    "United States Minor Outlying Islands",
                    "Uruguay",
                    "United States",
                    "Uzbekistan",
                    "Holy See (Vatican City State)",
                    "Saint Vincent and the Grenadines",
                    "Venezuela, Bolivarian Republic of",
                    "Virgin Islands, British",
                    "Virgin Islands, U.S.",
                    "Viet Nam",
                    "Vanuatu",
                    "Wallis and Futuna",
                    "Samoa",
                    "Yemen",
                    "South Africa",
                    "Zambia",
                    "Zimbabwe"
    };

    // array of country codes, used for accessing the api (order matters for index handling, same order as previous array)
    public static final String[] COUNTRY_CODES = {
              "ABW",
              "AFG",
              "AGO",
              "AIA",
              "ALA",
              "ALB",
              "AND",
              "ARE",
              "ARG",
              "ARM",
              "ASM",
              "ATA",
              "ATF",
              "ATG",
              "AUS",
              "AUT",
              "AZE",
              "BDI",
              "BEL",
              "BEN",
              "BES",
              "BFA",
              "BGD",
              "BGR",
              "BHR",
              "BHS",
              "BIH",
              "BLM",
              "BLR",
              "BLZ",
              "BMU",
              "BOL",
              "BRA",
              "BRB",
              "BRN",
              "BTN",
              "BVT",
              "BWA",
              "CAF",
              "CAN",
              "CCK",
              "CHE",
              "CHL",
              "CHN",
              "CIV",
              "CMR",
              "COD",
              "COG",
              "COK",
              "COL",
              "COM",
              "CPV",
              "CRI",
              "CUB",
              "CUW",
              "CXR",
              "CYM",
              "CYP",
              "CZE",
              "DEU",
              "DJI",
              "DMA",
              "DNK",
              "DOM",
              "DZA",
              "ECU",
              "EGY",
              "ERI",
              "ESH",
              "ESP",
              "EST",
              "ETH",
              "FIN",
              "FJI",
              "FLK",
              "FRA",
              "FRO",
              "FSM",
              "GAB",
              "GBR",
              "GEO",
              "GGY",
              "GHA",
              "GIB",
              "GIN",
              "GLP",
              "GMB",
              "GNB",
              "GNQ",
              "GRC",
              "GRD",
              "GRL",
              "GTM",
              "GUF",
              "GUM",
              "GUY",
              "HKG",
              "HMD",
              "HND",
              "HRV",
              "HTI",
              "HUN",
              "IDN",
              "IMN",
              "IND",
              "IOT",
              "IRL",
              "IRN",
              "IRQ",
              "ISL",
              "ISR",
              "ITA",
              "JAM",
              "JEY",
              "JOR",
              "JPN",
              "KAZ",
              "KEN",
              "KGZ",
              "KHM",
              "KIR",
              "KNA",
              "KOR",
              "KWT",
              "LAO",
              "LBN",
              "LBR",
              "LBY",
              "LCA",
              "LIE",
              "LKA",
              "LSO",
              "LTU",
              "LUX",
              "LVA",
              "MAC",
              "MAF",
              "MAR",
              "MCO",
              "MDA",
              "MDG",
              "MDV",
              "MEX",
              "MHL",
              "MKD",
              "MLI",
              "MLT",
              "MMR",
              "MNE",
              "MNG",
              "MNP",
              "MOZ",
              "MRT",
              "MSR",
              "MTQ",
              "MUS",
              "MWI",
              "MYS",
              "MYT",
              "NAM",
              "NCL",
              "NER",
              "NFK",
              "NGA",
              "NIC",
              "NIU",
              "NLD",
              "NOR",
              "NPL",
              "NRU",
              "NZL",
              "OMN",
              "PAK",
              "PAN",
              "PCN",
              "PER",
              "PHL",
              "PLW",
              "PNG",
              "POL",
              "PRI",
              "PRK",
              "PRT",
              "PRY",
              "PSE",
              "PYF",
              "QAT",
              "REU",
              "ROU",
              "RUS",
              "RWA",
              "SAU",
              "SDN",
              "SEN",
              "SGP",
              "SGS",
              "SHN",
              "SJM",
              "SLB",
              "SLE",
              "SLV",
              "SMR",
              "SOM",
              "SPM",
              "SRB",
              "SSD",
              "STP",
              "SUR",
              "SVK",
              "SVN",
              "SWE",
              "SWZ",
              "SXM",
              "SYC",
              "SYR",
              "TCA",
              "TCD",
              "TGO",
              "THA",
              "TJK",
              "TKL",
              "TKM",
              "TLS",
              "TON",
              "TTO",
              "TUN",
              "TUR",
              "TUV",
              "TWN",
              "TZA",
              "UGA",
              "UKR",
              "UMI",
              "URY",
              "USA",
              "UZB",
              "VAT",
              "VCT",
              "VEN",
              "VGB",
              "VIR",
              "VNM",
              "VUT",
              "WLF",
              "WSM",
              "YEM",
              "ZAF",
              "ZMB",
              "ZWE"
    };

    public static final int MIN_YEAR = 1960; // the minimum year you can choose
    public static final int MAX_YEAR = 2021; // the maximum year you can choose

    // array of the different analysis types, the first dataset described in each dataset is Forest area, analysis types 2-8 contain a second variable dataset
    public static final String[] ANALYSIS_TYPES = {"Forest area (% of land area)", "Forest area vs GDP growth (annual %)", "Forest area vs Manufacturing, value added (annual % growth)", "Forest area vs Agriculture, value added (% of GDP)", "Forest area vs Population, total", "Forest area vs Exports of goods and services (% of GDP)","Forest area vs Military expenditure (% of GDP)","Forest area vs Time required to start a business (days)"};

    // array of analysis types formatted as chart labels, the first string represents the forest area dataset while the remainder represent the variable dataset in the analysis type
    public static final String[] CHART_LABELS = {"Forest area (% of land area)", "GDP growth (annual %)", "Manufacturing, value added (annual % growth)", "Agriculture, value added (% of GDP)", "Population, total", "Exports of goods and services (% of GDP)","Military expenditure (% of GDP)","Time required to start a business (days)"};

    // array of api indicators for the analysis types, this array and the 2 previous ones should index identically
    public static final String[] INDICATORS = {"AG.LND.FRST.ZS", "NY.GDP.MKTP.KD.ZG", "NV.IND.MANF.KD.ZG", "NV.AGR.TOTL.ZS", "SP.POP.TOTL", "NE.EXP.GNFS.ZS","MS.MIL.XPND.GD.ZS","IC.REG.DURS"};

    // array of types of graph viewers you can choose
    public static final String[] VIEW_TYPES = {"Report", "Bar Chart", "Line Chart", "Scatter Plot"};


    /**
     * This method creates and returns an array of valid years based on passed min and max year.
     * @return an array of valid years as Integers (we can not use int primitives in a map or as a Comparable so we return an Integer[])
     */
    public static Integer[] getYearsInRange(int minYear, int maxYear) {
        Integer[] years = new Integer[maxYear + 1 - minYear]; // declare an array of the length from min year to max year
        for (int i = minYear; i <= maxYear; i++) { // loop from min to max year
            years[i-minYear] = i; // add the year to the array
        }
        return years;
    }

    /**
     * This method returns a list of the 2 analysis types being graphed, only called when 2 datasets are present
     * @return a String[] of the 2 analysis types
     */
    public static String[] getAnalysisList() {
        String[] analyses = {
                ANALYSIS_TYPES[0], // the forest analysis
                ANALYSIS_TYPES[MainUI.getAnalysisType()] // the variable analysis
        };
        return analyses;
    }


}
